import Head from 'next/head';
import Image from 'next/image';
import { useAccount, useConnect, useDisconnect } from 'wagmi';
import { InjectedConnector } from 'wagmi/connectors/injected';
import styles from '../styles/Home.module.css';

export default function Home() {
  const { address } = useAccount();
  const { connect } = useConnect({
    connector: new InjectedConnector(),
  });
  const { disconnect } = useDisconnect();
  console.log('basic nft address', process.env.NEXT_PUBLIC_BASIC_NFT_ADDRESS);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Basic NFT drop!</h1>

        {address && (
          <div className={styles.description}>
            You&apos;re connected to{' '}
            <code className={`${styles.code} about-link`}>{address}</code>
          </div>
        )}

        <div
          onClick={() => (address ? disconnect() : connect())}
          className={styles.grid}
        >
          <div className={styles.card}>
            <h2>{address ? 'Disconnect' : 'Connect'}</h2>
          </div>

          <div className={styles.card}>
            <h2>Mint</h2>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
