// packages
import Head from 'next/head';
import Image from 'next/image';

// styles
import styles from '../styles/Home.module.css';

import Layout from '../components/Layout/Layout';

// abi
// import basicNftAbi from '../../backend/deployments/localhost/BasicNft.json';

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Basic NFT drop!</h1>

          {/* {address && (
            <div className={styles.description}>
              You&quot;re connected to{' '}
              <code className={`${styles.code} about-link`}>{address}</code>
            </div>
          )}

          {write && (
            <div className={styles.grid}>
              <div onClick={() => write()} className={styles.card}>
                <h2>{isLoading ? 'Minting...' : 'Mint'}</h2>
              </div>
            </div>
          )} */}
        </main>

        {/* {isSuccess && (
          <div>
            Successfully minted your NFT!
            <div>
              <a href={`https://etherscan.io/tx/${data?.hash}`}>Etherscan</a>
            </div>
          </div>
        )} */}

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </Layout>
  );
}
