name: CI - Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '^14.15.0 || ^16.10.0 || >=18.0.0'
          check-latest: true

      - name: Install Npm Dependencies
        run: yarn install

      - name: Build App
        run: yarn build

      - name: Run tests with jest
        run: yarn test:ci

      - name: Cypress.io
        uses: cypress-io/github-action@v4.2.0
        with:
          working-directory: ./frontend
          start: yarn start
          wait-on: 'http://localhost:3000'